services:
  # Core telemetry infrastructure (80% of value)
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  # Simple telemetry validation (20% effort, 80% coverage)
  telemetry-test:
    image: python:3.12-slim
    command:
      [
        "sh",
        "-c",
        "echo 'Telemetry infrastructure ready' && echo 'Jaeger: http://localhost:16686' && echo 'Prometheus: http://localhost:9090' && echo 'Grafana: http://localhost:3000 (admin/admin)' && sleep 10",
      ]
    depends_on:
      - jaeger
      - prometheus
      - grafana
