# Terraform configuration for aws
# Generated by uvmgr with 8020 patterns: False

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

# 8020 Infrastructure Pattern
# Focus on high-value resources that provide 80% of the value
