# OpenTelemetry Collector Configuration for uvmgr
# This configuration sets up the collector to receive traces and metrics
# from uvmgr and export them to Jaeger and Prometheus

receivers:
  # OTLP receiver for traces and metrics
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  # Batch processor to optimize data export
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  # Add uvmgr-specific attributes to all telemetry
  attributes:
    actions:
      - key: service.namespace
        value: uvmgr
        action: upsert
      - key: deployment.environment
        value: development
        action: upsert

  # Memory limiter to prevent OOM
  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

exporters:
  # Export traces to Jaeger
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Export metrics to Prometheus
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: uvmgr
    const_labels:
      environment: development

  # Debug exporter for troubleshooting
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

  # File exporter for persistence
  file:
    path: /tmp/uvmgr-telemetry.json
    rotation:
      max_megabytes: 10
      max_days: 3
      max_backups: 3

extensions:
  # Health check extension
  health_check:
    endpoint: 0.0.0.0:13133
    path: /health

  # Performance profiler
  pprof:
    endpoint: 0.0.0.0:1777

  # zpages for debugging
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [health_check, pprof, zpages]
  
  pipelines:
    # Trace pipeline
    traces:
      receivers: [otlp]
      processors: [memory_limiter, attributes, batch]
      exporters: [otlp/jaeger, debug, file]
    
    # Metrics pipeline
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, attributes, batch]
      exporters: [prometheus, debug, file]
    
    # Logs pipeline (for future use)
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [debug, file]

  telemetry:
    logs:
      level: info
    metrics:
      level: detailed
      address: 0.0.0.0:8888