# #
# Auto-generated semantic convention constants for uvmgr.
# Generated from /Users/sac/dev/uvmgr/weaver-forge/registry
#
# DO NOT EDIT - this file is auto-generated by Weaver Forge.

"""
Semantic Convention Constants for uvmgr
==================================================

This module contains auto-generated semantic convention constants that provide
type-safe access to OpenTelemetry semantic convention attributes.

Generated on: 2025-06-27T22:54:03.624267
Weaver version: weaver 0.15.3
Registry: /Users/sac/dev/uvmgr/weaver-forge/registry
"""

from typing import Final


# CLI command attributes for uvmgr
class CliAttributes:
    """CLI command attributes for uvmgr"""
    
    CLI_COMMAND: Final[str] = "cli.command"  # The primary CLI command being executed
    
    CLI_SUBCOMMAND: Final[str] = "cli.subcommand"  # The subcommand if applicable
    
    CLI_EXIT_CODE: Final[str] = "cli.exit_code"  # The exit code of the CLI command
    
    COMMAND: Final[str] = "cli.command"  # Alias for CLI_COMMAND (compatibility)
    
    OPTIONS: Final[str] = "cli.options"  # CLI options and arguments
    
    EXIT_CODE: Final[str] = "cli.exit_code"  # Alias for CLI_EXIT_CODE (compatibility)
    


# Package management operation attributes
class PackageAttributes:
    """Package management operation attributes"""
    
    PACKAGE_NAME: Final[str] = "package.name"  # Name of the package being operated on
    
    PACKAGE_VERSION: Final[str] = "package.version"  # Version specification or resolved version
    
    PACKAGE_OPERATION: Final[str] = "package.operation"  # The type of package operation
    
    OPERATION: Final[str] = "package.operation"  # Alias for PACKAGE_OPERATION


# Security operation attributes
class SecurityAttributes:
    """Security operation attributes"""
    
    OPERATION: Final[str] = "security.operation"  # The type of security operation
    
    PROJECT_PATH: Final[str] = "security.project_path"  # Path being scanned
    
    SEVERITY_THRESHOLD: Final[str] = "security.severity_threshold"  # Minimum severity level
    
    SCAN_TYPE: Final[str] = "security.scan_type"  # Type of security scan
    
    VULNERABILITY_COUNT: Final[str] = "security.vulnerability_count"  # Number of vulnerabilities found
    
    ISSUES_FOUND: Final[str] = "security.issues_found"  # Total security issues detected
    
    SCAN_DURATION: Final[str] = "security.scan_duration"  # Time taken for security scan


# Security operation values
class SecurityOperations:
    """Standard security operation values"""
    
    SCAN: Final[str] = "scan"  # Comprehensive security scan
    
    AUDIT: Final[str] = "audit"  # Dependency vulnerability audit
    
    SECRETS: Final[str] = "secrets"  # Secret detection scan
    
    CODE: Final[str] = "code"  # Code security analysis
    
    CONFIG: Final[str] = "config"  # Security configuration review
    
    FIX: Final[str] = "fix"  # Vulnerability remediation
    
    DEV_DEPENDENCY: Final[str] = "package.dev_dependency"  # Whether it's a dev dependency
    





# Validation helpers
def validate_attribute(attribute_name: str, attribute_value: str) -> bool:
    """Validate that an attribute name and value are valid semantic conventions."""
    valid_attributes = {
        
        
        CliAttributes.CLI_COMMAND,
        
        CliAttributes.CLI_SUBCOMMAND,
        
        CliAttributes.CLI_EXIT_CODE,
        
        
        
        PackageAttributes.PACKAGE_NAME,
        
        PackageAttributes.PACKAGE_VERSION,
        
        PackageAttributes.PACKAGE_OPERATION,
        
        
    }
    return attribute_name in valid_attributes

# Process execution attributes
class ProcessAttributes:
    """Process execution attributes"""
    
    COMMAND: Final[str] = "process.command"  # Command being executed
    
    EXECUTABLE: Final[str] = "process.executable"  # Executable name
    
    EXIT_CODE: Final[str] = "process.exit_code"  # Process exit code
    
    WORKING_DIRECTORY: Final[str] = "process.working_directory"  # Working directory
    
    DURATION: Final[str] = "process.duration"  # Process execution duration


# Test execution attributes  
class TestAttributes:
    """Test execution attributes"""
    
    OPERATION: Final[str] = "test.operation"  # Test operation type
    
    FRAMEWORK: Final[str] = "test.framework"  # Testing framework
    
    TEST_COUNT: Final[str] = "test.count"  # Number of tests
    
    PASSED: Final[str] = "test.passed"  # Number of tests passed
    
    FAILED: Final[str] = "test.failed"  # Number of tests failed
    
    SKIPPED: Final[str] = "test.skipped"  # Number of tests skipped


# Tool integration attributes
class ToolAttributes:
    """Tool integration attributes"""
    
    TOOL_NAME: Final[str] = "tool.name"  # Name of the integrated tool
    
    TOOL_CATEGORY: Final[str] = "tool.category"  # Category of the tool
    
    TOOL_VERSION: Final[str] = "tool.version"  # Version of the tool
    
    TOOL_STATUS: Final[str] = "tool.status"  # Status of the tool (available, not_found, etc.)
    
    OPERATION: Final[str] = "tool.operation"  # Operation being performed with the tool
    
    INTEGRATION_ENGINE: Final[str] = "tool.integration_engine"  # Tool integration engine name
    
    CAPABILITIES: Final[str] = "tool.capabilities"  # Tool capabilities


# Tool operation types
class ToolOperations:
    """Tool operation types"""
    
    DISCOVER: Final[str] = "discover"  # Tool discovery operation
    
    EXECUTE: Final[str] = "execute"  # Tool execution operation
    
    HEALTH_CHECK: Final[str] = "health_check"  # Tool health check operation
    
    ROUTE: Final[str] = "route"  # Tool routing operation


# Test coverage attributes (continuation of TestAttributes)  
class TestCoverageAttributes:
    """Test coverage attributes"""
    
    COVERAGE_PERCENTAGE: Final[str] = "test.coverage_percentage"  # Test coverage percentage


# Plugin system attributes
class PluginAttributes:
    """Plugin system attributes"""
    
    PLUGIN_NAME: Final[str] = "plugin.name"  # Name of the plugin
    
    PLUGIN_VERSION: Final[str] = "plugin.version"  # Version of the plugin
    
    PLUGIN_TYPE: Final[str] = "plugin.type"  # Type of plugin (command, tool_adapter, etc.)
    
    PLUGIN_STATUS: Final[str] = "plugin.status"  # Status of the plugin
    
    PLUGIN_SYSTEM: Final[str] = "plugin.system"  # Plugin system name
    
    HOOK_TYPE: Final[str] = "plugin.hook_type"  # Type of hook being executed
    
    MARKETPLACE_SOURCE: Final[str] = "plugin.marketplace_source"  # Source of plugin


# Plugin operation types
class PluginOperations:
    """Plugin operation types"""
    
    DISCOVER: Final[str] = "discover"  # Plugin discovery operation
    
    LOAD: Final[str] = "load"  # Plugin load operation
    
    UNLOAD: Final[str] = "unload"  # Plugin unload operation
    
    INSTALL: Final[str] = "install"  # Plugin install operation
    
    UNINSTALL: Final[str] = "uninstall"  # Plugin uninstall operation
    
    EXECUTE_HOOK: Final[str] = "execute_hook"  # Hook execution operation


# Build operation attributes
class BuildAttributes:
    """Build operation attributes"""
    
    OPERATION: Final[str] = "build.operation"  # Build operation type
    
    TYPE: Final[str] = "build.type"  # Build type (wheel, exe, etc.)
    
    OUTPUT_PATH: Final[str] = "build.output_path"  # Output path
    
    SIZE: Final[str] = "build.size"  # Build artifact size


# Project creation attributes
class ProjectAttributes:
    """Project creation attributes"""
    
    NAME: Final[str] = "project.name"  # Project name
    
    LANGUAGE: Final[str] = "project.language"  # Programming language
    
    OPERATION: Final[str] = "project.operation"  # Project operation type


# Project operations
class ProjectOperations:
    """Standard project operation values"""
    
    CREATE: Final[str] = "create"


# AI operation attributes
class AIAttributes:
    """AI operation attributes"""
    
    OPERATION: Final[str] = "ai.operation"  # AI operation type
    
    MODEL: Final[str] = "ai.model"  # AI model name
    
    PROVIDER: Final[str] = "ai.provider"  # AI provider
    
    TOKENS_INPUT: Final[str] = "ai.tokens.input"  # Input tokens
    
    TOKENS_OUTPUT: Final[str] = "ai.tokens.output"  # Output tokens
    
    COST: Final[str] = "ai.cost"  # Operation cost


# CI operation attributes
class CIAttributes:
    """CI operation attributes"""
    
    OPERATION: Final[str] = "ci.operation"  # CI operation type
    
    RUNNER: Final[str] = "ci.runner"  # CI runner type
    
    ENVIRONMENT: Final[str] = "ci.environment"  # Environment type
    
    TEST_COUNT: Final[str] = "ci.test_count"  # Number of tests
    
    PASSED: Final[str] = "ci.passed"  # Number passed
    
    FAILED: Final[str] = "ci.failed"  # Number failed
    
    DURATION: Final[str] = "ci.duration"  # Duration in seconds
    
    SUCCESS_RATE: Final[str] = "ci.success_rate"  # Success rate percentage


# CI operations
class CIOperations:
    """Standard CI operation values"""
    
    VERIFY: Final[str] = "verify"
    
    QUICK_TEST: Final[str] = "quick_test"
    
    RUN: Final[str] = "run"


# Workflow attributes
class WorkflowAttributes:
    """Workflow execution attributes"""
    
    OPERATION: Final[str] = "workflow.operation"  # Workflow operation type
    
    TYPE: Final[str] = "workflow.type"  # Workflow type (bpmn, etc.)
    
    DEFINITION_PATH: Final[str] = "workflow.definition_path"  # Path to workflow definition
    
    DEFINITION_NAME: Final[str] = "workflow.definition_name"  # Workflow name
    
    ENGINE: Final[str] = "workflow.engine"  # Workflow engine


# Workflow operations
class WorkflowOperations:
    """Standard workflow operation values"""
    
    RUN: Final[str] = "run"
    
    VALIDATE: Final[str] = "validate"
    
    PARSE: Final[str] = "parse"


# Package operations
class PackageOperations:
    """Standard package operation values"""
    
    ADD: Final[str] = "add"
    
    REMOVE: Final[str] = "remove"
    
    UPDATE: Final[str] = "update"
    
    LIST: Final[str] = "list"
    
    SYNC: Final[str] = "sync"


# Release operation attributes
class ReleaseAttributes:
    """Release operation attributes"""
    
    VERSION: Final[str] = "release.version"  # Release version
    
    TYPE: Final[str] = "release.type"  # Release type (major, minor, patch)
    
    OPERATION: Final[str] = "release.operation"  # Release operation type


# Release operations
class ReleaseOperations:
    """Standard release operation values"""
    
    BUMP: Final[str] = "bump"
    
    CHANGELOG: Final[str] = "changelog"
    
    TAG: Final[str] = "tag"


# Tool management attributes
class ToolAttributes:
    """Tool management attributes"""
    
    TOOL_NAME: Final[str] = "tool.name"  # Name of the tool
    
    OPERATION: Final[str] = "tool.operation"  # Tool operation type
    
    ISOLATED: Final[str] = "tool.isolated"  # Whether tool runs in isolated environment
    
    PACKAGE_COUNT: Final[str] = "tool.package_count"  # Number of packages
    
    CATEGORY: Final[str] = "tool.category"  # Tool category
    
    RECOMMENDATION_COUNT: Final[str] = "tool.recommendation_count"  # Number of recommendations
    
    HEALTH_STATUS: Final[str] = "tool.health_status"  # Health status
    
    PROFILE: Final[str] = "tool.profile"  # Tool profile name


# Tool operations
class ToolOperations:
    """Standard tool operation values"""
    
    INSTALL: Final[str] = "install"
    
    RUN: Final[str] = "run"
    
    UNINSTALL: Final[str] = "uninstall"
    
    LIST: Final[str] = "list"
    
    DIRECTORY: Final[str] = "directory"
    
    RECOMMEND: Final[str] = "recommend"
    
    HEALTH_CHECK: Final[str] = "health_check"
    
    SYNC: Final[str] = "sync"


# uvx-specific attributes
class UvxAttributes:
    """uvx-specific attributes for isolated tool management"""
    
    OPERATION: Final[str] = "uvx.operation"  # uvx operation type
    
    PACKAGE: Final[str] = "uvx.package"  # Package name
    
    TOOL: Final[str] = "uvx.tool"  # Tool name
    
    PYTHON_VERSION: Final[str] = "uvx.python_version"  # Python version
    
    FORCE: Final[str] = "uvx.force"  # Force reinstall flag
    
    TOOL_COUNT: Final[str] = "uvx.tool_count"  # Number of tools
    
    CATEGORY: Final[str] = "uvx.category"  # Tool category
    
    RECOMMENDATION_COUNT: Final[str] = "uvx.recommendation_count"  # Recommendations
    
    HEALTH_STATUS: Final[str] = "uvx.health_status"  # Health status


# uvx operations
class UvxOperations:
    """Standard uvx operation values"""
    
    INSTALL: Final[str] = "install"
    
    RUN: Final[str] = "run"
    
    LIST: Final[str] = "list"
    
    UNINSTALL: Final[str] = "uninstall"
    
    UPGRADE: Final[str] = "upgrade"
    
    RECOMMEND: Final[str] = "recommend"
    
    HEALTH_CHECK: Final[str] = "health_check"


# Cache management attributes
class CacheAttributes:
    """Cache management attributes"""
    
    OPERATION: Final[str] = "cache.operation"  # Cache operation type
    
    SIZE: Final[str] = "cache.size"  # Cache size in bytes
    
    TYPE: Final[str] = "cache.type"  # Cache type (global, local, etc.)
    
    PATH: Final[str] = "cache.path"  # Cache directory path
    
    ITEM_COUNT: Final[str] = "cache.item_count"  # Number of cached items


# Cache operations
class CacheOperations:
    """Standard cache operation values"""
    
    CLEAR: Final[str] = "clear"
    
    SIZE: Final[str] = "size"
    
    DIR: Final[str] = "dir"


# Index management attributes
class IndexAttributes:
    """Index management attributes"""
    
    OPERATION: Final[str] = "index.operation"  # Index operation type
    
    URL: Final[str] = "index.url"  # Index URL


# Index operations
class IndexOperations:
    """Standard index operation values"""
    
    ADD: Final[str] = "add"
    
    REMOVE: Final[str] = "remove"
    
    LIST: Final[str] = "list"


# Remote operation attributes
class RemoteAttributes:
    """Remote operation attributes"""
    
    OPERATION: Final[str] = "remote.operation"  # Remote operation type
    
    URL: Final[str] = "remote.url"  # Remote URL
    
    BRANCH: Final[str] = "remote.branch"  # Git branch
    
    COMMIT: Final[str] = "remote.commit"  # Git commit hash


# Remote operations
class RemoteOperations:
    """Standard remote operation values"""
    
    CLONE: Final[str] = "clone"
    
    PULL: Final[str] = "pull"
    
    PUSH: Final[str] = "push"


# Search operation attributes
class SearchAttributes:
    """Search operation attributes"""
    
    OPERATION: Final[str] = "search.operation"  # Search operation type
    
    QUERY: Final[str] = "search.query"  # Search query
    
    RESULTS_COUNT: Final[str] = "search.results_count"  # Number of results
    
    SOURCE: Final[str] = "search.source"  # Search source


# Search operations
class SearchOperations:
    """Standard search operation values"""
    
    PACKAGE: Final[str] = "package"
    
    FILE: Final[str] = "file"
    
    CODE: Final[str] = "code"


# Server operation attributes
class ServerAttributes:
    """Server operation attributes"""
    
    OPERATION: Final[str] = "server.operation"  # Server operation type
    
    HOST: Final[str] = "server.host"  # Server host
    
    PORT: Final[str] = "server.port"  # Server port
    
    PROTOCOL: Final[str] = "server.protocol"  # Server protocol


# Server operations
class ServerOperations:
    """Standard server operation values"""
    
    START: Final[str] = "start"
    
    STOP: Final[str] = "stop"
    
    RESTART: Final[str] = "restart"


# Shell operation attributes
class ShellAttributes:
    """Shell operation attributes"""
    
    OPERATION: Final[str] = "shell.operation"  # Shell operation type
    
    COMMAND: Final[str] = "shell.command"  # Shell command
    
    WORKING_DIR: Final[str] = "shell.working_dir"  # Working directory
    
    EXIT_CODE: Final[str] = "shell.exit_code"  # Exit code


# Shell operations
class ShellOperations:
    """Standard shell operation values"""
    
    EXECUTE: Final[str] = "execute"
    
    INTERACTIVE: Final[str] = "interactive"
    
    BACKGROUND: Final[str] = "background"


# MCP (Model Context Protocol) attributes
class McpAttributes:
    """MCP operation attributes"""
    
    OPERATION: Final[str] = "mcp.operation"  # MCP operation type
    
    TOOL_NAME: Final[str] = "mcp.tool_name"  # Tool name
    
    RESOURCE_URI: Final[str] = "mcp.resource_uri"  # Resource URI
    
    STATUS: Final[str] = "mcp.status"  # Operation status


# MCP operations
class McpOperations:
    """Standard MCP operation values"""
    
    CALL_TOOL: Final[str] = "call_tool"
    
    LIST_TOOLS: Final[str] = "list_tools"
    
    READ_RESOURCE: Final[str] = "read_resource"
    
    LIST_RESOURCES: Final[str] = "list_resources"


# GitHub-specific attributes
class GitHubAttributes:
    """GitHub-specific semantic convention attributes."""
    OWNER = "github.owner"
    REPOSITORY = "github.repository"
    WORKFLOW_NAME = "github.workflow.name"
    WORKFLOW_RUN_ID = "github.workflow.run_id"
    WORKFLOW_STATUS = "github.workflow.status"
    WORKFLOW_CONCLUSION = "github.workflow.conclusion"
    WORKFLOW_EVENT = "github.workflow.event"
    WORKFLOW_BRANCH = "github.workflow.branch"


# Export all classes for convenient importing
__all__ = [
    "CliAttributes",
    "PackageAttributes",
    "PackageOperations",
    "ProcessAttributes",
    "TestAttributes", 
    "BuildAttributes",
    "ProjectAttributes",
    "ProjectOperations",
    "ReleaseAttributes",
    "ReleaseOperations",
    "ToolAttributes",
    "ToolOperations",
    "UvxAttributes",
    "UvxOperations",
    "CacheAttributes",
    "CacheOperations",
    "IndexAttributes", 
    "IndexOperations",
    "RemoteAttributes",
    "RemoteOperations",
    "SearchAttributes",
    "SearchOperations",
    "ServerAttributes",
    "ServerOperations",
    "ShellAttributes",
    "ShellOperations",
    "McpAttributes",
    "McpOperations",
    "AIAttributes",
    "CIAttributes",
    "CIOperations",
    "WorkflowAttributes",
    "WorkflowOperations",
    "validate_attribute",
    "GitHubAttributes",
]