version: '3.8'

services:
  uvmgr-terraform-test:
    build:
      context: ../../
      dockerfile: docker/cleanroom-terraform-test/Dockerfile
    volumes:
      - test-results:/test-workspace/results
      - benchmark-data:/test-workspace/benchmarks
    environment:
      - PYTHONPATH=/app/src
      - OTEL_RESOURCE_ATTRIBUTES=service.name=uvmgr-terraform-test,service.version=cleanroom,environment=docker
      - OTEL_SERVICE_NAME=uvmgr-terraform-test
      - DOCKER_ENV=true
    command: /test-scripts/run-cleanroom-tests.sh

  # Optional: OTEL Collector for observability testing
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - otel-data:/tmp/otel
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger

  # Optional: Jaeger for trace visualization
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true

volumes:
  test-results:
  benchmark-data:
  otel-data: