# Prometheus Configuration for DoD Validation
# ===========================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics

  - job_name: 'uvmgr-dod-validation'
    static_configs:
      - targets: ['dod-validator:8080']
    scrape_interval: 5s
    metrics_path: /metrics
    honor_labels: true